// user
const USE_USER_REFRESH_INTERVAL = 1000 * 60 * 5; // 5 minutes
const USE_USERS_REFRESH_INTERVAL = 1000 * 60 * 5; // 5 minutes

// organization
const USE_ORGANIZATION_INFO_REFRESH_INTERVAL = 0;
const USE_ORGANIZATION_WITH_CHILDREN_REFRESH_INTERVAL = 0;

// balance
const USE_BALANCES_REFRESH_INTERVAL = 1000 * 30; // 30 seconds
const USD_SYSTEM_BALANCE_REFRESH_INTERVAL = 1000 * 30; // 30 seconds

// ip-whitelist
const USE_ORGANIZATION_IP_WHITELISTS_REFRESH_INTERVAL = 1000 * 30; // 30 seconds

// transaction
const USE_TRANSACTION_REFRESH_INTERVAL = 1000 * 30; // 30 seconds
const USE_TRANSACTION_METADATA_REFRESH_INTERVAL = 1000 * 30; // 30 seconds
const USE_SYSTEM_DAILY_TRANSACTION_COUNT_REFRESH_INTERVAL = 1000 * 60 * 5; // 5 minutes
const USE_DAILY_TRANSACTION_COUNT_BY_ORGANIZATION_ID_REFRESH_INTERVAL =
  1000 * 60 * 5; // 5 minutes

export {
  USE_USER_REFRESH_INTERVAL,
  USE_USERS_REFRESH_INTERVAL,
  USE_ORGANIZATION_INFO_REFRESH_INTERVAL,
  USE_ORGANIZATION_WITH_CHILDREN_REFRESH_INTERVAL,
  USE_BALANCES_REFRESH_INTERVAL,
  USD_SYSTEM_BALANCE_REFRESH_INTERVAL,
  USE_ORGANIZATION_IP_WHITELISTS_REFRESH_INTERVAL,
  USE_TRANSACTION_REFRESH_INTERVAL,
  USE_TRANSACTION_METADATA_REFRESH_INTERVAL,
  USE_SYSTEM_DAILY_TRANSACTION_COUNT_REFRESH_INTERVAL,
  USE_DAILY_TRANSACTION_COUNT_BY_ORGANIZATION_ID_REFRESH_INTERVAL,
};
