export enum UnsettledBalanceType {
  // adding
  DEPOSIT_INCOME = 'DEPOSIT_INCOME',
  ADMIN_REVENUE = 'ADMIN_REVENUE',
  AGENT_REVENUE = 'AGENT_REVENUE',

  // subtracting
  ADMIN_REVENUE_ROLLBACK_DUE_TO_WITHDRAWAL_REFUNDED = 'ADMIN_REVENUE_ROLLBACK_DUE_TO_WITHDRAWAL_REFUNDED',
  AGENT_REVENUE_ROLLBACK_DUE_TO_WITHDRAWAL_REFUNDED = 'AGENT_REVENUE_ROLLBACK_DUE_TO_WITHDRAWAL_REFUNDED',
}
