export enum PaymentChannel {
  // NATIVE_GCASH_QR
  NATIVE_GCASH_QR_GOLDPAY = "NATIVE_GCASH_QR_GOLDPAY",

  // NATIVE_GCASH_DIRECT
  NATIVE_GCASH_DIRECT_GOLDPAY = "NATIVE_GCASH_DIRECT_GOLDPAY",
  NATIVE_GCASH_DIRECT_BIFU = "NATIVE_GCASH_DIRECT_BIFU",

  // SIMULATED_GCASH_QR

  // SIMULATED_GCASH_DIRECT

  // MAYA
  MAYA_GOLDPAY = "MAYA_GOLDPAY",

  // QRPH
}
