export enum PaymentChannel {
  /*
   * BIFU
   */
  /* NATIVE_GCASH Deposit */
  NATIVE_GCASH_DIRECT_BIFU = "NATIVE_GCASH_DIRECT_BIFU", // 110
  NATIVE_GCASH_QR_BIFU = "NATIVE_GCASH_QR_BIFU", // 111
  NATIVE_GCASH_AWAKEN_BIFU = "NATIVE_GCASH_AWAKEN_BIFU", // 113
  NATIVE_GCASH_AWAKEN_REVISION_BIFU = "NATIVE_GCASH_AWAKEN_REVISION_BIFU", // 114
  /* NATIVE_GCASH Withdrawal */
  NATIVE_GCASH_BIFU_BANK = "NATIVE_GCASH_BIFU_BANK", // 100

  /* QRPH Deposit */
  QRPH_BIFU_DEPOSIT = "QRPH_BIFU_DEPOSIT", // 112
  /* QRPH Withdrawal */
  QRPH_BIFU_BANK_WITHDRAWAL = "QRPH_BIFU_BANK_WITHDRAWAL", // 100

  /* MAYA Deposit */
  MAYA_BIFU_DEPOSIT = "MAYA_BIFU_DEPOSIT", // 107
  /* MAYA Withdrawal */
  MAYA_BIFU_BANK_WITHDRAWAL = "MAYA_BIFU_BANK_WITHDRAWAL", // 100

  /*
   * IPAY
   */
  /* NATIVE_GCASH Deposit */
  NATIVE_GCASH_IPAY_DEPOSIT = "NATIVE_GCASH_IPAY_DEPOSIT",
  /* NATIVE_GCASH Withdrawal */
  NATIVE_GCASH_IPAY_WITHDRAWAL = "NATIVE_GCASH_IPAY_BANK_WITHDRAWAL",
}
