export enum PaymentMethod {
  // NATIVE GCASH
  NATIVE_GCASH_QR = 'NATIVE_GCASH_QR',
  NATIVE_GCASH_DIRECT = 'NATIVE_GCASH_DIRECT',

  // SIMULATED GCASH
  SIMULATED_GCASH_QR = 'SIMULATED_GCASH_QR',
  SIMULATED_GCASH_DIRECT = 'SIMULATED_GCASH_DIRECT',

  // MAYA
  MAYA = 'MAYA',

  // QRPH
  QRPH = 'QRPH',
}
