export enum PaymentChannel {
  // /*
  //  * BIFU
  //  */
  // /* NATIVE_GCASH Deposit */
  // NATIVE_GCASH_DIRECT_BIFU = 'NATIVE_GCASH_DIRECT_BIFU', // 110
  // NATIVE_GCASH_QR_BIFU = 'NATIVE_GCASH_QR_BIFU', // 111
  // NATIVE_GCASH_AWAKEN_BIFU = 'NATIVE_GCASH_AWAKEN_BIFU', // 113
  // NATIVE_GCASH_AWAKEN_CASHIER_BIFU = 'NATIVE_GCASH_AWAKEN_CASHIER_BIFU', // 113 (cashier)
  // NATIVE_GCASH_AWAKEN_REVISION_BIFU = 'NATIVE_GCASH_AWAKEN_REVISION_BIFU', // 114
  // /* NATIVE_GCASH Withdrawal */
  // NATIVE_GCASH_BIFU_BANK = 'NATIVE_GCASH_BIFU_BANK', // 100

  // /* QRPH Deposit */
  // QRPH_BIFU_DEPOSIT = 'QRPH_BIFU_DEPOSIT', // 112
  // /* QRPH Withdrawal */
  // QRPH_BIFU_BANK_WITHDRAWAL = 'QRPH_BIFU_BANK_WITHDRAWAL', // 100

  // /* MAYA Deposit */
  // MAYA_BIFU_DEPOSIT = 'MAYA_BIFU_DEPOSIT', // 107
  // /* MAYA Withdrawal */
  // MAYA_BIFU_BANK_WITHDRAWAL = 'MAYA_BIFU_BANK_WITHDRAWAL', // 100

  // /*
  //  * IPAY
  //  */
  // /* NATIVE_GCASH Deposit */
  // NATIVE_GCASH_IPAY_DEPOSIT = 'NATIVE_GCASH_IPAY_DEPOSIT',
  // NATIVE_GCASH_IPAY_CASHIER_DEPOSIT = 'NATIVE_GCASH_IPAY_CASHIER_DEPOSIT',
  // /* NATIVE_GCASH Withdrawal */
  // NATIVE_GCASH_IPAY_WITHDRAWAL = 'NATIVE_GCASH_IPAY_WITHDRAWAL',

  // /* QRPH Deposit */
  // QRPH_IPAY_DEPOSIT = 'QRPH_IPAY_DEPOSIT',
  // /* QRPH Withdrawal */
  // QRPH_IPAY_WITHDRAWAL = 'QRPH_IPAY_WITHDRAWAL',

  // /*
  //  * WorldPay
  //  */
  // /* NATIVE_GCASH Withdrawal */
  // NATIVE_GCASH_WORLDPAY_WITHDRAWAL = 'NATIVE_GCASH_WORLDPAY_WITHDRAWAL',
  // /* QRPH Withdrawal */
  // QRPH_WORLDPAY_WITHDRAWAL = 'QRPH_WORLDPAY_WITHDRAWAL',
  // /* MAYA Withdrawal */
  // MAYA_WORLDPAY_WITHDRAWAL = 'MAYA_WORLDPAY_WITHDRAWAL',

  // /*
  //  * DaliPay
  //  */
  // // NATIVE_GCASH Deposit
  // NATIVE_GCASH_DALIPAY_DEPOSIT = 'NATIVE_GCASH_DALIPAY_DEPOSIT',
  // // NATIVE_GCASH Withdrawal
  // NATIVE_GCASH_DALIPAY_WITHDRAWAL = 'NATIVE_GCASH_DALIPAY_WITHDRAWAL',

  // /*
  //  * OdPay
  //  */
  // // NATIVE_GCASH Withdrawal
  // NATIVE_GCASH_ODPAY_WITHDRAWAL = 'NATIVE_GCASH_ODPAY_WITHDRAWAL',

  /*
   * HFPay
   */
  // NATIVE_GCASH Deposit
  NATIVE_GCASH_HFPAY_DEPOSIT = "NATIVE_GCASH_HFPAY_DEPOSIT",
  // NATIVE_GCASH Withdrawal
  NATIVE_GCASH_HFPAY_WITHDRAWAL = "NATIVE_GCASH_HFPAY_WITHDRAWAL",

  // /*
  //  * QRPAY
  //  */
  // // NATIVE_GCASH Deposit
  // NATIVE_GCASH_QRPAY_DEPOSIT = 'NATIVE_GCASH_QRPAY_DEPOSIT',
  // NATIVE_GCASH_QRPAY_C1_DEPOSIT = 'NATIVE_GCASH_QRPAY_C1_DEPOSIT',
  // // NATIVE_GCASH Withdrawal
  // NATIVE_GCASH_QRPAY_WITHDRAWAL = 'NATIVE_GCASH_QRPAY_WITHDRAWAL',
  // NATIVE_GCASH_QRPAY_C1_WITHDRAWAL = 'NATIVE_GCASH_QRPAY_C1_WITHDRAWAL',

  // /*
  //  * APAY
  //  */
  // // NATIVE_GCASH Deposit
  // NATIVE_GCASH_APAY_DEPOSIT = 'NATIVE_GCASH_APAY_DEPOSIT',
  // // NATIVE_GCASH Withdrawal
  // NATIVE_GCASH_APAY_WITHDRAWAL = 'NATIVE_GCASH_APAY_WITHDRAWAL',

  // /*
  //  * TKINGPAY
  //  */
  // // NATIVE_GCASH Withdrawal
  // NATIVE_GCASH_TKINGPAY_WITHDRAWAL = 'NATIVE_GCASH_TKINGPAY_WITHDRAWAL',

  // /*
  //  * H88PAY
  //  */
  // // NATIVE_GCASH Deposit
  // NATIVE_GCASH_H88PAY_DEPOSIT = "NATIVE_GCASH_H88PAY_DEPOSIT",
  // // NATIVE_GCASH Withdrawal
  // NATIVE_GCASH_H88PAY_WITHDRAWAL = "NATIVE_GCASH_H88PAY_WITHDRAWAL",

  /*
   * SMPAY
   */
  // NATIVE_GCASH Deposit
  NATIVE_GCASH_SMPAY_DEPOSIT = "NATIVE_GCASH_SMPAY_DEPOSIT",
  // NATIVE_GCASH Withdrawal
  NATIVE_GCASH_SMPAY_WITHDRAWAL = "NATIVE_GCASH_SMPAY_WITHDRAWAL",
}
