export enum TransactionLogAction {
  TRANSACTION_CREATED = "TRANSACTION_CREATED",
  SUBMIT_TO_UPSTREAM = "SUBMIT_TO_UPSTREAM",
  UPSTREAM_RESPONSE = "UPSTREAM_RESPONSE",
  TRANSACTION_SUCCESS = "TRANSACTION_SUCCESS",
  TRANSACTION_FAILED = "TRANSACTION_FAILED",

  // Admin actions
  SET_TO_FAILED_BY_ADMIN = "SET_TO_FAILED_BY_ADMIN",
  RESUBMISSION_TRIGGERED = "RESUBMISSION_TRIGGERED",
  APPROVED_MERCHANT_REQUESTED_WITHDRAWAL = "APPROVED_MERCHANT_REQUESTED_WITHDRAWAL",
  REJECTED_MERCHANT_REQUESTED_WITHDRAWAL = "REJECTED_MERCHANT_REQUESTED_WITHDRAWAL",

  SEND_NOTIFICATION_TO_MERCHANT = "SEND_NOTIFICATION_TO_MERCHANT",
  MANUALLY_TRIGGER_NOTIFICATION_TO_MERCHANT = "MANUALLY_TRIGGER_NOTIFICATION_TO_MERCHANT",
  REVENUE_DISTRIBUTED = "REVENUE_DISTRIBUTED",
}
